name: Matrix Demo 
on: push
jobs:
    build:
        strategy:
            matrix:
                node-version: [12, 14, 16]
                operating-system: [ubuntu-latest, windows-latest, macos-latest]
        runs-on : ${{matrix.operating-system}}
        steps:
            - name : Get Code
              uses: action/checkout@v4
            - name: Install Node JS
              uses: action/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
            - name: Install Dependencies
              run: npm ci 
            - name: Build Code
              run: npm run build
        