name: Matrix Demo 
on: [push, workflow_dispatch]
jobs:
    build:
        strategy:
            matrix:
                node-version: [15, 16, 17]
                operating-system: [ubuntu-latest, windows-latest]
                exclude:
                    - node-version: 15
                      operating-system: windows-latest
        runs-on : ${{matrix.operating-system}}
        steps:
            - name : Get Code
              uses: actions/checkout@v4
            - name: Install Node JS
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}
            - name: Install Dependencies
              run: npm ci 
            - name: Build Code
              run: npm run build
        